plugins {
    id 'java'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'top.nontage'
version = '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = "https://jitpack.io"
    }
    maven {
        name = "fan87Repo"
        url = uri("https://repo.fan87.zip/snapshots")
        credentials {
            username = project.findProperty("fan87repo.user")?.toString()
            password = project.findProperty("fan87repo.key")?.toString()
        }
    }
}

dependencies {
    implementation("me.fan87:native-instrumentation-native-linux-x86_64:1.0-SNAPSHOT")
    implementation("me.fan87:native-instrumentation-native-windows-x86_64:1.0-SNAPSHOT")
    implementation("me.fan87:native-instrumentation:1.0-SNAPSHOT")
    implementation("org.javassist:javassist:3.30.2-GA")
    implementation("org.ow2.asm:asm:9.8")
    implementation("org.ow2.asm:asm-tree:9.8")
    implementation("org.ow2.asm:asm-util:9.8")
    compileOnly("top.nontage.auth:NontageAuthServer-Library:1.0-SNAPSHOT")
}

test {
    useJUnitPlatform()
}

tasks.shadowJar {
    archiveClassifier.set(null)
    relocate 'javassist', 'top.nontage.relocated.javassist'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact(tasks.shadowJar) {
                classifier = 'all'
            }

            groupId = group
            artifactId = project.name
            version = version
        }
    }
}


