package top.nontage.jniil.test.injector.instruction;

import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import top.nontage.jniil.annotations.At;
import top.nontage.jniil.annotations.InjectMethodInfo;
import top.nontage.jniil.injector.insn.InsnContext;
import top.nontage.jniil.interfaces.InsnInjectable;
import top.nontage.jniil.test.target.InstructionTarget;

import static org.objectweb.asm.Opcodes.*;

/**
 * INSTRUCTION INJECTOR EXAMPLE 3: PUTFIELD Field Access Tracing
 *
 * <p>This injector targets the {@code PUTFIELD} (Put Field) instruction
 * in the {@code InstructionTarget.toggleStatus()} method.</p>
 *
 * <p><b>What it does:</b></p>
 * <ul>
 *   <li>Anchors at the PUTFIELD instruction with {@code shiftAfter = true}</li>
 *   <li>Injects a custom {@code System.out.println} call right after the field is updated</li>
 * </ul>
 *
 * <p><b>Effect on program behavior:</b></p>
 * <ul>
 *   <li>Original: toggles the status flag, then prints the new state</li>
 *   <li>Modified: toggles the status flag, then prints a trace message, then prints the new state</li>
 * </ul>
 *
 * <p><b>Injected code:</b></p>
 * <pre>
 * System.out.println("[ASM] Field mutation detected via PUTFIELD!");
 * </pre>
 *
 * <p><b>Use case:</b></p>
 * This pattern is useful for:
 * <ul>
 *   <li>Auditing field modifications</li>
 *   <li>Debugging state changes in complex systems</li>
 *   <li>Monitoring object mutation without modifying source code</li>
 * </ul>
 *
 * <p><b>Design Note:</b></p>
 * Unlike FunctionalInjector which can have multiple methods in one class,
 * each Instruction injector class can only target ONE injection point.
 * Therefore, each injection scenario has its own separate class file.
 *
 * <p><b>Operational Principle:</b></p>
 * This class handles low-level runtime bytecode manipulation using the ASM tree API.
 * The framework intercepts the target method's instruction list (InsnList) as an ASM
 * MethodNode, locates the bytecode anchor specified by the {@code @At} annotation,
 * then directly links your custom InsnList into the underlying JVM execution stack
 * at runtime.
 *
 * @see InsnInjectable
 * @see At
 * @see InjectMethodInfo
 */
public class InstructionPutfieldExample implements InsnInjectable {

    /*
     * @At(opcode = PUTFIELD, shiftAfter = true):
     * Anchors the injection point immediately AFTER a PUTFIELD opcode operation concludes.
     *
     * This implementation injects a custom System.out.println call right after the field is updated.
     *
     * ASM bytecode generated by this injection:
     *   GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
     *   LDC "[ASM] Field mutation detected via PUTFIELD!"
     *   INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
     */
    @InjectMethodInfo(
            targetType = InstructionTarget.class,
            targetMethodName = "toggleStatus"
    )
    @At(opcode = PUTFIELD, shiftAfter = true)
    @Override
    public InsnList apply(InsnContext ctx, InsnList insns) {
        // Build: System.out.println("[ASM] Field mutation detected via PUTFIELD!");
        insns.add(new FieldInsnNode(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;"));
        insns.add(new LdcInsnNode("[ASM] Field mutation detected via PUTFIELD!"));
        insns.add(new MethodInsnNode(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false));
        return insns;
    }
}