name: JNIIL CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11, 17, 21, 22, 25]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout JNIIL
        uses: actions/checkout@v4
        with:
          path: jniil

      - name: Checkout JvmContext
        uses: actions/checkout@v4
        with:
          repository: SeanMud0319/JvmContext
          path: JvmContext

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Install JvmContext to local maven
        run: cd JvmContext && mvn install -DskipTests

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Make gradlew executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x jniil/gradlew

      - name: Run all tests
        run: cd jniil && ./gradlew testFunctional --stacktrace \ -Dorg.gradle.jvmargs="--add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/sun.instrument=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Djdk.attach.allowAttachSelf=true"